# Base configs
#baseurl: "https://pictrace.de"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_root: "images"
image_fulls_loc: "fulls"
image_thumbs_loc: "thumbs"
#google_analytics: ""

contact: "https://script.google.com/macros/s/AKfycbxbdT2UtNF7rD1fwgbFgd2f02hyOtUTMCQwDAKBTQwA0nUUlSwrvwO4p2hE9zd6_nPq/exec"

# UI configs
title: "Photography by Alexander Dümont"
subtitle: "Capturing Moments, One Frame at a Time!"
author: "Alexander Dümont"
header:
 title: "Photography"
 subtitle: "by Alexander Dümont"
footer:
 name: "Hello world, time to shine"
 bio1: "I'm learning and practicing photography: focus, aperture, shutter, focal distance, composition, lighting, color grades. That's a lot!"
 bio2: "Of course I'm aware of modern AI generated and supported imagery. This is my attempt to understand and cherish the manual effort to photography."
web_design: "AJ"
# sponsor # no sponsor
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  #twitter: ""
  #instagram: ""
  #dribbble: ""
  #linkedin: ""
  github: "https://www.github.com/a-d"
